### ISSUE TITLE
何かの Model Collection View の Class を作る

### ISSUE THREAD

**Issue by neotag** [Pixel-Gaji/info#1]
@sou-lab @tacamy

**Comment by nakajmg** [comment]
複数ある電球の状態を管理するクラスを作る
- 電球のModel
  - on/off
  - 色とか
- 電球のCollection
  - Collectionから各電球を操作するメソッド
    - 全部off/全部on

### （できたら）
- 電球のView

## フォルダ

ソースコードは各自のリポジトリの`src/0`フォルダに入れる。
